version: '3.2'

services:

  test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 20080:8000
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      # - ./app:/app/app
      # - ./bootstrap:/app/bootstrap
      # - ./config:/app/config
      # - ./database:/app/database
      # - ./public:/app/public 
      # - ./resources:/app/resources
      # - ./routes:/app/routes
      # - ./storage:/app/storage
      # - ./test:/app/test
      # - ./tests:/app/tests
      # - ./.env:/app/.env
      #- ./vendor:/app/vendor
      - ./:/app
    networks:
      - test

      

  mysql:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=Ubuxa##99
      - MYSQL_DATABASE=forge
      - MYSQL_USER=forge
      - MYSQL_PASSWORD=Ubuxa##99
    networks:
      - test

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 5050:80
    environment:
      - PMA_HOST=mysql
      - PMA_PASSWORD=Ubuxa##99
    restart: unless-stopped
    volumes:
    # Re-use local composer cache via host-volume
    - ~/.composer-docker/cache:/root/.composer/cache:delegated
    # Mount source-code for development
    - ./:/app
    networks:
      - test
  
networks:
  test:
    driver: bridge
